### ISSUE TITLE
[Docs]Support light vs dark mode display of Meshery logo in README

### ISSUE THREAD

**Issue by KrishAryan** [meshery/meshery-operator#314]
#### Current State
There are some logos in README.md that have very low contrast in either light/dark mode 

#### Desired State
Change the docs such that there is a separate logo for dark/light mode with high contrast

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by KrishAryan** [comment]
//assign

**Comment by exitflynn** [comment]
Hello there! This'll be my first time contributing to Meshery (and any open source project to be honest :P) and I'd love to take up this issue!

**Comment by exitflynn** [comment]
Hey @KrishAryan! The current logos are those which should be displayed in light-mode and to work on this issue, I'll require images that should be displayed in the dark-mode. Out of the four logos, I managed to find the dark-mode version of two from another meshery repository (meshery/meshery). The two which are left with a light-mode only image are the main Meshery logo and the Meshery Operator logo. There is a subtle difference between the two logos used in this repository (meshery/meshery-operator) and meshery/meshery. I can take the light and dark versions of the main logo from there and incorporate them into this repo if that'd be okay.

Or maybe is there any resource that I'm unaware of where I can find the images? (The Figma link given in the issue does not work, it essentially says 'either file not found or you don't have access'. Do let me know if something like this is what I should rather open an issue about.) Also is it time I opened a pull request so that you can see what I changed, how it looks and have a better idea of what I'm talking about?

Also this is my first time actually doing this and so please feel free to provide any constructive criticism without any hesitation, I would be very thankful.

Thanks a lot for your time!

**Comment by KrishAryan** [comment]
@exitflynn have you attended any newcomers meet? 
If not then you can watch this 
https://www.youtube.com/watch?v=RsyydIUT6UI&list=PL3A-A6hPO2INVEknQ4R-VwDMUT9yM_FSm 
or read this
https://docs.google.com/document/d/1tpg2sLxirozNt3Ofr3GdM002f9rExp74EqrsGZBU710/edit

**Comment by KrishAryan** [comment]
Also, try to join the slack channel and ask meshmates about the logo library. They can give you the link.

**Comment by leecalcote** [comment]
Dark mode version of the Meshery logo and the Meshery Operator logo are not displaying.

**Comment by K0more** [comment]
@leecalcote hey can I get assigned to this issue?

**Comment by K0more** [comment]
@KrishAryan hey krish I have some doubts, would you like to clear them?

**Comment by KrishAryan** [comment]
Sure

**Comment by K0more** [comment]
@KrishAryan I cleared them on slack, ty for the response though!
